### ISSUE TITLE
Better tabs design :: Sidebar overlay

### ISSUE THREAD

**Issue by hashd** [hashd/Marvelous#10]

**Comment by praveenpuglia** [comment]
Quick question - How does the file switching work then? They click on **hamburger** icon and see the files and then do it ? I tried to imagine my own workflow that way, and it seems tedious. 

OR 

This forces people to use <kbd>CTRL</kbd>+<kbd>P</kbd>. Which is okay from the power user point of view. But if this is for writers, they will probably also want to **print** in which case, the shortcut is now not available.

**Comment by hashd** [comment]
Nice thought, for now lets provide the user the option to hide the tab bar

**Comment by praveenpuglia** [comment]
BTW, I don't have rights to assign this to me.

**Comment by praveenpuglia** [comment]
Another idea i have is to instead of making this part of some kind of settings panel, let's give this as a toggle button on the tabs bar on the far right. this should get. What say?

**Comment by praveenpuglia** [comment]
So based on #13, can you mark this closed?
